const waterfalls = [
    {
        id: "multnomah",
        name: "Multnomah Falls",
        region: "Columbia Gorge",
        difficulty: "Easy",
        distance: "2.4 miles round trip (to upper viewpoint)",
        pets: false,
        parking: "Large lot beside Historic Highway and I-84 Exit 31; fills early on weekends.",
        bestSeason: "Spring and early summer for peak flow; year-round access.",
        tips: "Stay behind railings on the Benson Bridge. Ice can form on steps in winter.",
        hiddenGem: false,
        featured: true,
        image: "images/Multnomah-Falls.webp",
        alt: "Tall twin-tier Multnomah Falls cascading through a forested canyon"
    },
    {
        id: "latourell",
        name: "Latourell Falls",
        region: "Columbia Gorge",
        difficulty: "Easy",
        distance: "2.4 miles loop",
        pets: true,
        parking: "Pullout at Guy W. Talbot State Park along the Historic Highway.",
        bestSeason: "Spring through fall; moss walls glow after rain.",
        tips: "The short paved path to the base is wheelchair-friendly in dry conditions.",
        hiddenGem: false,
        featured: true,
        image: "images/Latourell-Falls.webp",
        alt: "Latourell Falls plunging past lichen-covered basalt cliffs"
    },
    {
        id: "wahkeena",
        name: "Wahkeena Falls",
        region: "Columbia Gorge",
        difficulty: "Moderate",
        distance: "2.8 miles round trip via Wahkeena Trail",
        pets: true,
        parking: "Wahkeena Falls Trailhead lot west of Multnomah Falls.",
        bestSeason: "Late spring when cascades are fullest.",
        tips: "Connect to Fairy Falls for a longer loop; carry water on warm days.",
        hiddenGem: false,
        featured: false,
        image: "images/Wahkeena-Falls.webp",
        alt: "Wahkeena Falls spilling over mossy rock near a trail bridge"
    },
    {
        id: "ponytail",
        name: "Ponytail Falls",
        region: "Columbia Gorge",
        difficulty: "Moderate",
        distance: "About 2 miles round trip from Oneonta Trailhead",
        pets: true,
        parking: "Oneonta Gorge / Horsetail Falls area parking along the Historic Highway.",
        bestSeason: "Spring and early summer.",
        tips: "You can walk behind the curtain of water—expect slick rock and spray.",
        hiddenGem: true,
        featured: false,
        image: "images/Ponytail-Falls.webp",
        alt: "Hikers walking behind the curtain of Ponytail Falls"
    },
    {
        id: "punchbowl",
        name: "Punchbowl Falls",
        region: "Columbia Gorge",
        difficulty: "Easy",
        distance: "4 miles round trip on Eagle Creek Trail",
        pets: false,
        parking: "Eagle Creek Trailhead near Cascade Locks; Northwest Forest Pass often required.",
        bestSeason: "Late spring to early fall when the trail is clear of ice.",
        tips: "Watch for cliff exposure along Eagle Creek. No dogs on this popular trail.",
        hiddenGem: false,
        featured: false,
        image: "images/Punchbowl-Falls.webp",
        alt: "Punchbowl Falls pouring into a turquoise pool in Eagle Creek canyon"
    },
    {
        id: "wahclella",
        name: "Wahclella Falls",
        region: "Columbia Gorge",
        difficulty: "Moderate",
        distance: "2 miles round trip",
        pets: true,
        parking: "Wahclella Falls Trailhead near Bonneville Dam; Northwest Forest Pass.",
        bestSeason: "Spring for strong flow; shaded canyon stays cool in summer.",
        tips: "The loop includes bridges and stairs—sturdy shoes help after rain.",
        hiddenGem: true,
        featured: false,
        image: "images/Wahclella_Falls.webp",
        alt: "Wahclella Falls pouring through a lush green canyon"
    },
    {
        id: "tamanawas",
        name: "Tamanawas Falls",
        region: "Mount Hood",
        difficulty: "Moderate",
        distance: "3.6 miles round trip",
        pets: true,
        parking: "Sherwood Campground / Highway 35 trailhead east of Mount Hood.",
        bestSeason: "Summer and early fall when snow has melted from the creek trail.",
        tips: "The final approach crosses rocky creek bed—poles are useful.",
        hiddenGem: false,
        featured: false,
        image: "images/Tamanawas-Falls-Trail.webp",
        alt: "Wide curtain of Tamanawas Falls at the end of a forest trail"
    },
    {
        id: "ramona",
        name: "Ramona Falls",
        region: "Mount Hood",
        difficulty: "Moderate",
        distance: "7.1 miles loop",
        pets: true,
        parking: "Ramona Falls Trailhead near Zigzag; Northwest Forest Pass.",
        bestSeason: "July through September for snow-free trails.",
        tips: "River crossings can be swift in early season—check conditions before you go.",
        hiddenGem: false,
        featured: true,
        image: "images/ramona-falls-trail.webp",
        alt: "Ramona Falls cascading over columnar basalt in a forest clearing"
    },
    {
        id: "little-zigzag",
        name: "Little Zigzag Falls",
        region: "Mount Hood",
        difficulty: "Easy",
        distance: "0.6 miles round trip",
        pets: true,
        parking: "Small pullout on Forest Road 2639 near Rhododendron.",
        bestSeason: "Late spring through fall.",
        tips: "A short, family-friendly walk with a rewarding basalt amphitheater view.",
        hiddenGem: true,
        featured: false,
        image: "images/Little-Zigzag-Falls.webp",
        alt: "Little Zigzag Falls flowing over mossy volcanic rock"
    },
    {
        id: "sahalie-koosah",
        name: "Sahalie and Koosah Falls",
        region: "Cascades",
        difficulty: "Easy",
        distance: "2.6 miles Waterfalls Loop Trail",
        pets: true,
        parking: "Sahalie Falls and Koosah Falls viewpoints on Highway 126.",
        bestSeason: "Late spring and summer; McKenzie River runs strong after snowmelt.",
        tips: "Stay on signed viewpoints—cliffs above the river are sheer and unfenced in places.",
        hiddenGem: false,
        featured: false,
        image: "images/Sahalie-and-Koosah-Falls.webp",
        alt: "Powerful Sahalie Falls on the McKenzie River"
    },
    {
        id: "proxy",
        name: "Proxy Falls",
        region: "Cascades",
        difficulty: "Easy",
        distance: "1.6 miles loop",
        pets: true,
        parking: "Proxy Falls Trailhead on Highway 242 (seasonal road).",
        bestSeason: "July to October when the McKenzie Pass Highway is open.",
        tips: "Lava fields reflect heat—bring sun protection even on short hikes.",
        hiddenGem: false,
        featured: false,
        image: "images/Proxy-Falls.webp",
        alt: "Proxy Falls draping a wide cliff face in the Cascades"
    },
    {
        id: "toketee",
        name: "Toketee Falls",
        region: "Southern Oregon",
        difficulty: "Easy",
        distance: "0.8 miles round trip",
        pets: true,
        parking: "Toketee Falls Trailhead off Road 34 near Highway 138.",
        bestSeason: "Spring through fall; viewpoint is dramatic after rain.",
        tips: "Stairs lead to the overlook—watch children near the railing.",
        hiddenGem: false,
        featured: true,
        image: "images/Toketee-Falls.webp",
        alt: "Two-tier Toketee Falls framed by columnar basalt"
    },
    {
        id: "watson",
        name: "Watson Falls",
        region: "Southern Oregon",
        difficulty: "Moderate",
        distance: "0.8 miles round trip",
        pets: true,
        parking: "Watson Falls Trailhead near Highway 138 east of Roseburg.",
        bestSeason: "Spring for maximum height and mist.",
        tips: "One of Oregon’s tallest single drops—trail can be muddy and rooted.",
        hiddenGem: false,
        featured: false,
        image: "images/watson-falls.webp",
        alt: "Tall Watson Falls plunging into a rocky gorge"
    },
    {
        id: "salt-creek",
        name: "Salt Creek Falls",
        region: "Cascades",
        difficulty: "Easy",
        distance: "0.2 miles to viewpoint; longer options available",
        pets: true,
        parking: "Salt Creek Falls Observation Site off Highway 58.",
        bestSeason: "Late spring through early fall.",
        tips: "Paved path to the overlook makes this a great stop for all ages.",
        hiddenGem: false,
        featured: false,
        image: "images/Salt-Creek-Falls.webp",
        alt: "Salt Creek Falls dropping into a deep forested canyon"
    },
    {
        id: "clearwater",
        name: "Clearwater Falls",
        region: "Southern Oregon",
        difficulty: "Easy",
        distance: "0.3 miles round trip",
        pets: true,
        parking: "Clearwater Falls Campground pullouts on Highway 138.",
        bestSeason: "Summer for camping combos; spring for flow.",
        tips: "Short boardwalk-style access—combine with nearby Toketee or Watson.",
        hiddenGem: true,
        featured: false,
        image: "images/clearwater-falls.webp",
        alt: "Clearwater Falls spilling over a wide rocky ledge"
    },
    {
        id: "mill-creek",
        name: "Mill Creek Falls",
        region: "Southern Oregon",
        difficulty: "Easy",
        distance: "0.7 miles round trip",
        pets: true,
        parking: "Mill Creek Falls Trailhead near Prospect.",
        bestSeason: "Spring and early summer.",
        tips: "Also view Barr Creek Falls from the same short trail network.",
        hiddenGem: false,
        featured: false,
        image: "images/Mill-Creek-Falls.webp",
        alt: "Mill Creek Falls plunging into a rocky pool near Prospect"
    },
    {
        id: "tumalo",
        name: "Tumalo Falls",
        region: "Central Oregon",
        difficulty: "Easy",
        distance: "0.5 miles to viewpoint; longer loops available",
        pets: true,
        parking: "Tumalo Falls Day Use Area west of Bend; fee site in summer.",
        bestSeason: "Late spring through fall; road may close with snow.",
        tips: "Arrive early on summer weekends—the lot fills quickly.",
        hiddenGem: false,
        featured: false,
        image: "images/tumalo-falls.webp",
        alt: "Tumalo Falls cascading beside a forest overlook near Bend"
    },
    {
        id: "steelhead",
        name: "Steelhead Falls",
        region: "Central Oregon",
        difficulty: "Easy",
        distance: "2 miles round trip",
        pets: true,
        parking: "Steelhead Falls Trailhead near Terrebonne.",
        bestSeason: "Spring and fall for milder desert temperatures.",
        tips: "Exposed canyon trail—bring sun protection and extra water.",
        hiddenGem: true,
        featured: false,
        image: "images/Steelhead-Falls.webp",
        alt: "Steelhead Falls on the Deschutes River in a desert canyon"
    },
    {
        id: "willamette",
        name: "Willamette Falls",
        region: "Willamette Valley",
        difficulty: "Easy",
        distance: "Viewpoint access; walking paths in Oregon City",
        pets: true,
        parking: "Public lots near downtown Oregon City viewpoints.",
        bestSeason: "Year-round; dramatic after winter storms.",
        tips: "An urban waterfall stop—pair with historic downtown Oregon City.",
        hiddenGem: false,
        featured: false,
        image: "images/Willamette-Falls.webp",
        alt: "Wide Willamette Falls beside Oregon City industry and bridges"
    },
    {
        id: "munson-creek",
        name: "Munson Creek Falls",
        region: "Coast",
        difficulty: "Easy",
        distance: "0.6 miles round trip",
        pets: true,
        parking: "Munson Creek Falls County Park south of Tillamook.",
        bestSeason: "Late fall through spring when coastal rains feed the falls.",
        tips: "One of the tallest falls in the Coast Range—trail can be muddy.",
        hiddenGem: false,
        featured: false,
        image: "images/munson-creek-falls.webp",
        alt: "Munson Creek Falls tumbling through a coastal forest canyon"
    },
    {
        id: "sweet-creek",
        name: "Sweet Creek Falls",
        region: "Coast",
        difficulty: "Easy",
        distance: "2.2 miles round trip along Sweet Creek Trail",
        pets: true,
        parking: "Sweet Creek Trailheads near Mapleton / Highway 126.",
        bestSeason: "Winter and spring for a string of cascades.",
        tips: "Metal walkways can be slick when wet—use caution with kids.",
        hiddenGem: false,
        featured: false,
        image: "images/Sweet-Creek-Falls.webp",
        alt: "Sweet Creek Falls along a lush coastal rainforest trail"
    },
    {
        id: "susan-creek",
        name: "Susan Creek Falls",
        region: "Southern Oregon",
        difficulty: "Easy",
        distance: "1.6 miles round trip",
        pets: true,
        parking: "Susan Creek Day Use Area on Highway 138.",
        bestSeason: "Spring through fall.",
        tips: "Gentle trail suitable for families; combine with other North Umpqua stops.",
        hiddenGem: false,
        featured: false,
        image: "images/Susan-Creek-Falls.webp",
        alt: "Susan Creek Falls pouring into a rocky pool"
    },
    {
        id: "mcdowell",
        name: "McDowell Creek Falls",
        region: "Willamette Valley",
        difficulty: "Easy",
        distance: "1.5 to 3 miles of park loop options",
        pets: true,
        parking: "McDowell Creek Falls County Park near Lebanon.",
        bestSeason: "Winter and spring for strongest cascades.",
        tips: "Several named falls in one park—Royal Terrace and Majestic are favorites.",
        hiddenGem: true,
        featured: false,
        image: "images/McDowell-Creek-Falls.webp",
        alt: "McDowell Creek Falls surrounded by green forest near Lebanon"
    },
    {
        id: "youngs-river",
        name: "Youngs River Falls",
        region: "Coast",
        difficulty: "Easy",
        distance: "Roadside viewpoint with short walk",
        pets: true,
        parking: "Pullout on Youngs River Road south of Astoria.",
        bestSeason: "Late fall through spring.",
        tips: "Quick scenic stop near Astoria—respect private property boundaries.",
        hiddenGem: true,
        featured: false,
        image: "images/young-river-falls.webp",
        alt: "Youngs River Falls near Astoria under overcast coastal skies"
    }
];

const regions = [
    "Columbia Gorge",
    "Mount Hood",
    "Cascades",
    "Central Oregon",
    "Southern Oregon",
    "Willamette Valley",
    "Coast"
];
